version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src # This mounts your local code into the container for live-reloading
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload